### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by andreygolovin** [YotpoLtd/magento2-plugin#35] opened 2016-10-17 12:59 UTC
Hello,
Thanks for great module.

Looks like **"cacheable=false"** attribute in default.xml make entire page response non-cacheable.

`<block class="Yotpo\Yotpo\Block\Conversion" name="yotpo_conversion" template="conversion.phtml" cacheable="false"/>`

From Magento 2 [docs](http://devdocs.magento.com/guides/v2.1/config-guide/cache/cache-priv-over.html):

> To create an uncacheable page, mark any block on that page as uncacheable in the layout using cacheable="false".

**Comment by Tjitse-E** [comment] 2017-05-11 11:54
@andreygolovin you are right. I've just tested the issue with yotpo/module-review 2.1. I can confirm that this module breaks full page cache when enabled. This makes the module unusable for production!

With Yotpo disabled: 
![developer_tools_-_http___www_magehostdev_pro_](https://cloud.githubusercontent.com/assets/14849044/25947671/bb565236-3650-11e7-858d-e4dea03d0da7.png)

With Yotpo enabled:
![developer_tools_-_http___www_magehostdev_pro_](https://cloud.githubusercontent.com/assets/14849044/25947736/f9b78a22-3650-11e7-8650-3910dbacbc89.png)

You should use private data instead: http://devdocs.magento.com/guides/v2.0/config-guide/cache/cache-priv-priv.html

**Comment by billykov** [comment] 2017-05-11 13:32
Hi all, 
Thanks for bringing this up - we are checking it.
We will update here once we have news.

**Comment by billykov** [comment] 2017-06-28 13:38
Update:
We added this fix to the roadmap, and it is expected to be released with the next version of our extension.
Unfortunately, I don't have ETAs yet

**Comment by HOSTED-POWER** [comment] 2017-08-14 08:36
Hi, any update? Sites cannot use the cache because of this at all.

**Comment by Tjitse-E** [comment] 2017-12-06 13:38
@billykov come on, how can this bug not be fixed after one year? Who knows how many Magento 2 installations have broken Full Page Caching because of this...

**Comment by andreygolovin** [comment] 2017-12-06 13:54
@Tjitse-E it seams that this issue was fixed [here](https://github.com/YotpoLtd/magento2-plugin/commit/809fe911df4570030b4c3dc3a9c5e663d88bd3cd
) :)

So at the moment cache will be off for "checkout_onepage_success" which is much better than for "default".

**Comment by billykov** [comment] 2017-12-06 18:42
Hey guys, 
Sorry, it was fixed, but forgot to update this thread.

We gotta keep the checkout un-cached for tracking purpose, but the rest of the cache is now unharmed.

**Closed by billykov** 2017-12-06 18:42 UTC
Labels: bug
